SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF INNER JOIN ICECREAM_INFO
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
GROUP BY FLAVOR
HAVING SUM(FIRST_HALF.TOTAL_ORDER) > 3000
ORDER BY SUM(FIRST_HALF.TOTAL_ORDER) DESC